# Pulls every level's portal surfaces out of the generated PSP geometry,
# for harness.c. Run from the repository root.
import re, glob, sys
out = []
names = []
for f in sorted(glob.glob('build/psp/codegen/assets/test_chambers/*/*_geo.c')):
    s = open(f).read()
    level = f.split('/')[-2]
    verts = {m.group(1): [(int(a), int(b)) for a, b in re.findall(r'\.x = (-?\d+), \.y = (-?\d+)', m.group(2))]
             for m in re.finditer(r'struct Vector2s16 (\w+)\[\] = \{(.*?)\n\};', s, re.S)}
    edges = {m.group(1): [tuple(int(x) for x in e) for e in re.findall(r'\.nextEdge = (\d+), \.pointIndex = (\d+), \.prevEdge = (\d+), \.reverseEdge = (\d+)', m.group(2))]
             for m in re.finditer(r'struct SurfaceEdge (\w+)\[\] = \{(.*?)\n\};', s, re.S)}
    blk = re.search(r'struct PortalSurface \w+_portal_surfaces\[\] = \{(.*?)\n\};', s, re.S)
    if not blk: continue
    for i, e in enumerate(re.findall(r'\{\n(.*?)\n    \}', blk.group(1), re.S)):
        vec = lambda k: [float(x) for x in re.search(r'\.%s = \{\.x = ([-\de.]+), \.y = ([-\de.]+), \.z = ([-\de.]+)\}' % k, e).groups()]
        vn = re.search(r'\.vertices = &(\w+)\[0\]', e).group(1)
        en = re.search(r'\.edges = &(\w+)\[0\]', e).group(1)
        names.append('%s #%d %s' % (level, i, vn))
        out.append((verts[vn], edges[en], vec('right'), vec('up'), vec('corner')))
print('// generated by extract.py')
print('#define SURFACE_COUNT %d' % len(out))
for n, (v, e, r, u, c) in enumerate(out):
    print('static struct Vector2s16 sV%d[] = {%s};' % (n, ','.join('{{{%d,%d}}}' % p for p in v)))
    print('static struct SurfaceEdge sE%d[] = {%s};' % (n, ','.join('{%d,%d,%d,%d}' % (pi, ne, pe, re_) for ne, pi, pe, re_ in e)))
print('static struct PortalSurface sSurfaces[] = {')
for n, (v, e, r, u, c) in enumerate(out):
    print('  {sV%d, sE%d, %d, %d, 0, 0, {%r,%r,%r}, {%r,%r,%r}, {%r,%r,%r}, 0, 0},' % ((n, n, len(e), len(v)) + tuple(float(x) for x in r + u + c)))
print('};')
print('static const char* sNames[] = {%s};' % ','.join('"%s"' % x for x in names))
