# The sounds the game has, in the order the sound id table is generated from.
# The N64 and PSP paths both read this; only what they run per sound differs.
#
# The order is not decorative: generate_sound_ids.js requires a language's
# localized sounds to be contiguous, and that is what the loop over languages
# in assets/sound/CMakeLists.txt produces.

set(SOUND_SCRIPTS
    ambient/alarms/portal_elevator_chime.sox
    ambient/atmosphere/ambience_base.sox
    ambient/dinosaur_fizzle.sox
    ambient/energy/zap1.sox
    ambient/energy/zap2.sox
    ambient/energy/zap3.sox
    ambient/machines/fluorescent_hum_1.sox
    ambient/machines/portalgun_rotate1.sox
    ambient/machines/ticktock1.sox
    ambient/machines/wall_move5.sox
    ambient/music/looping_radio_mix.sox
    ambient/music/valve.sox
    buttons/button10.sox
    buttons/button3.sox
    common/wpn_denyselect.sox
    common/wpn_select.sox
    doors/door_metal_thin_close2.sox
    doors/doormove1.jsox
    doors/doormove2.sox
    doors/garage_stop1.sox
    npc/turret_floor/active.sox
    npc/turret_floor/deploy.sox
    npc/turret_floor/die.sox
    npc/turret_floor/ping.sox
    npc/turret_floor/retract.sox
    npc/turret_floor/shoot1.jsox
    physics/flesh/flesh_impact_bullet1.sox
    physics/flesh/flesh_impact_bullet2.sox
    physics/flesh/flesh_impact_bullet3.sox
    physics/flesh/flesh_impact_bullet4.sox
    physics/flesh/flesh_impact_bullet5.sox
    plats/elevator_stop1.sox
    player/footsteps/concrete1.sox
    player/footsteps/concrete2.sox
    player/footsteps/concrete3.sox
    player/footsteps/concrete4.sox
    player/portal_enter1.sox
    player/portal_enter2.sox
    player/portal_exit1.sox
    player/portal_exit2.sox
    ui/buttonclickrelease.sox
    ui/buttonrollover.sox
    vehicles/apc/apc_idle1.jsox
    vehicles/apc/apc_shutdown.sox
    vehicles/apc/apc_start_loop3.jsox
    vo/aperture_ai/ding_off.sox
    vo/aperture_ai/ding_on.sox
    weapons/cguard/charging.sox
    weapons/physcannon/energy_bounce1.sox
    weapons/physcannon/energy_disintegrate4.sox
    weapons/physcannon/energy_sing_explosion2.sox
    weapons/physcannon/energy_sing_flyby1.sox
    weapons/physcannon/energy_sing_loop4.sox
    weapons/portalgun/portal_close1.sox
    weapons/portalgun/portal_close2.jsox
    weapons/portalgun/portal_fizzle2.sox
    weapons/portalgun/portal_open1.jsox
    weapons/portalgun/portal_open2.jsox
    weapons/portalgun/portal_open3.sox
    weapons/portalgun/portalgun_shoot_blue1.sox
    weapons/portalgun/portalgun_shoot_red1.sox
    weapons/stunstick/alyx_stunner1.sox
)

set(LOCALIZED_SOUND_SCRIPTS
    npc/turret_floor/turret_active_1.sox
    npc/turret_floor/turret_active_2.sox
    npc/turret_floor/turret_active_4.sox
    npc/turret_floor/turret_active_5.sox
    npc/turret_floor/turret_active_6.sox
    npc/turret_floor/turret_active_7.sox
    npc/turret_floor/turret_active_8.sox
    npc/turret_floor/turret_autosearch_1.sox
    npc/turret_floor/turret_autosearch_2.sox
    npc/turret_floor/turret_autosearch_4.sox
    npc/turret_floor/turret_autosearch_5.sox
    npc/turret_floor/turret_autosearch_6.sox
    npc/turret_floor/turret_collide_1.sox
    npc/turret_floor/turret_collide_2.sox
    npc/turret_floor/turret_collide_3.sox
    npc/turret_floor/turret_collide_4.sox
    npc/turret_floor/turret_collide_5.sox
    npc/turret_floor/turret_deploy_1.sox
    npc/turret_floor/turret_deploy_2.sox
    npc/turret_floor/turret_deploy_4.sox
    npc/turret_floor/turret_deploy_5.sox
    npc/turret_floor/turret_deploy_6.sox
    npc/turret_floor/turret_disabled_2.sox
    npc/turret_floor/turret_disabled_4.sox
    npc/turret_floor/turret_disabled_5.sox
    npc/turret_floor/turret_disabled_6.sox
    npc/turret_floor/turret_disabled_7.sox
    npc/turret_floor/turret_disabled_8.sox
    npc/turret_floor/turret_search_1.sox
    npc/turret_floor/turret_search_2.sox
    npc/turret_floor/turret_search_4.sox
    npc/turret_floor/turret_fizzler_1.sox
    npc/turret_floor/turret_pickup_1.sox
    npc/turret_floor/turret_pickup_3.sox
    npc/turret_floor/turret_pickup_6.sox
    npc/turret_floor/turret_pickup_7.sox
    npc/turret_floor/turret_pickup_8.sox
    npc/turret_floor/turret_pickup_9.sox
    npc/turret_floor/turret_pickup_10.sox
    npc/turret_floor/turret_retire_1.sox
    npc/turret_floor/turret_retire_2.sox
    npc/turret_floor/turret_retire_4.sox
    npc/turret_floor/turret_retire_5.sox
    npc/turret_floor/turret_retire_6.sox
    npc/turret_floor/turret_retire_7.sox
    npc/turret_floor/turret_tipped_2.sox
    npc/turret_floor/turret_tipped_4.sox
    npc/turret_floor/turret_tipped_5.sox
    npc/turret_floor/turret_tipped_6.sox
    vo/aperture_ai/00_part1_entry-1.sox
    vo/aperture_ai/00_part1_entry-2.sox
    vo/aperture_ai/00_part1_entry-3.sox
    vo/aperture_ai/00_part1_entry-4.sox
    vo/aperture_ai/00_part1_entry-5.sox
    vo/aperture_ai/00_part1_entry-6.sox
    vo/aperture_ai/00_part1_entry-7.sox
    vo/aperture_ai/00_part1_success-1.sox
    vo/aperture_ai/00_part1_success-2.sox
    vo/aperture_ai/00_part1_success-3.sox
    vo/aperture_ai/00_part2_entry-1.sox
    vo/aperture_ai/00_part2_success-1.sox
    vo/aperture_ai/01_part1_entry-1.sox
    vo/aperture_ai/01_part1_entry-2.sox
    vo/aperture_ai/01_part1_get_portal_gun-1.sox
    vo/aperture_ai/01_part1_get_portal_gun-2.sox
    vo/aperture_ai/01_part1_get_portal_gun-3.sox
    vo/aperture_ai/01_part1_get_portal_gun-4.sox
    vo/aperture_ai/01_part1_get_portal_gun-5.sox
    vo/aperture_ai/01_part1_get_portal_gun-6.sox
    vo/aperture_ai/01_part1_get_portal_gun-7.sox
    vo/aperture_ai/01_part1_get_portal_gun-8.sox
    vo/aperture_ai/01_part2_entry-1.sox
    vo/aperture_ai/01_part2_success-1.sox
    vo/aperture_ai/02_part1_entry-1.sox
    vo/aperture_ai/02_part1_entry-2.sox
    vo/aperture_ai/02_part1_success-1.sox
    vo/aperture_ai/02_part1_success-2.sox
    vo/aperture_ai/02_part2_success-1.sox
    vo/aperture_ai/02_part2_success-2.sox
    vo/aperture_ai/03_part1_entry-1.sox
    vo/aperture_ai/03_part1_entry-2.sox
    vo/aperture_ai/03_part1_success-1.sox
    vo/aperture_ai/03_part2_entry-1.sox
    vo/aperture_ai/03_part2_platform_activated-1.sox
    vo/aperture_ai/04_part1_entry-1.sox
    vo/aperture_ai/04_part1_success-1.sox
    vo/aperture_ai/05_part1_entry-1.sox
    vo/aperture_ai/05_part1_entry-2.sox
    vo/aperture_ai/05_part1_nag1-1.sox
    vo/aperture_ai/05_part1_nag2-1.sox
    vo/aperture_ai/05_part1_nag3-1.sox
    vo/aperture_ai/05_part1_nag4-1.sox
    vo/aperture_ai/05_part1_nag5-1.sox
    vo/aperture_ai/05_part1_success-1.sox
    vo/aperture_ai/06_part1_entry-1.sox
    vo/aperture_ai/06_part1_success_1-1.sox
    vo/aperture_ai/06_part1_success_2-1.sox
    vo/aperture_ai/07_part1_entry-1.sox
    vo/aperture_ai/07_part1_entry-2.sox
    vo/aperture_ai/07_part1_entry-3.sox
    vo/aperture_ai/07_part1_get_device_component-1.sox
    vo/aperture_ai/07_part1_get_device_component-2.sox
    vo/aperture_ai/07_part1_get_device_component-3.sox
    vo/aperture_ai/07_part1_trapped-1.sox
    vo/aperture_ai/07_part1_trapped-2.sox
    vo/aperture_ai/07_part2_entry-1.sox
    vo/aperture_ai/07_part2_success-1.sox
    vo/aperture_ai/08_part1_entry-1.sox
    vo/aperture_ai/08_part1_entry-2.sox
    vo/aperture_ai/08_part1_entry-3.sox
    vo/aperture_ai/08_part1_success-1.sox
    vo/aperture_ai/08_part1_success-2.sox
    vo/aperture_ai/08_part1_trapped-1.sox
    vo/aperture_ai/08_part1_trapped-2.sox
    vo/aperture_ai/09_part1_entry-1.sox
    vo/aperture_ai/09_part1_entry-2.sox
    vo/aperture_ai/09_part1_success-1.sox
    vo/aperture_ai/10_part1_entry-1.sox
    vo/aperture_ai/10_part1_entry-2.sox
    vo/aperture_ai/10_part1_entry-3.sox
    vo/aperture_ai/10_part1_success-1.sox
    vo/aperture_ai/11_part1_entry-1.sox
    vo/aperture_ai/11_part1_entry-2.sox
    vo/aperture_ai/11_part1_entry-3.sox
    vo/aperture_ai/11_part1_success-1.sox
    vo/aperture_ai/13_part1_end-1.sox
    vo/aperture_ai/13_part1_end-2.sox
    vo/aperture_ai/13_part1_end-3.sox
    vo/aperture_ai/13_part1_endnag-1.sox
    vo/aperture_ai/13_part1_endnag-2.sox
    vo/aperture_ai/13_part1_endnag-3.sox
    vo/aperture_ai/13_part1_endnag-4.sox
    vo/aperture_ai/13_part1_endnag-5.sox
    vo/aperture_ai/13_part1_endnag-6.sox
    vo/aperture_ai/13_part1_endnag-7.sox
    vo/aperture_ai/13_part1_endnag-8.sox
    vo/aperture_ai/13_part1_entry-1.sox
    vo/aperture_ai/13_part1_euthanized-1.sox
    vo/aperture_ai/13_part1_middle-1.sox
    vo/aperture_ai/13_part1_middle-2b-1.sox
    vo/aperture_ai/13_part1_middle-2b-2.sox
    vo/aperture_ai/13_part1_middle-2.sox
    vo/aperture_ai/13_part1_pickup-1.sox
    vo/aperture_ai/escape_01_part1_nag01-1.sox
    vo/aperture_ai/generic_crate_vaporized_in_emancipation_grid-1.sox
    vo/aperture_ai/generic_crate_vaporized_in_emancipation_grid-2.sox
    vo/aperture_ai/generic_security_camera_destroyed-1.sox
    vo/aperture_ai/generic_security_camera_destroyed-2.sox
    vo/aperture_ai/generic_security_camera_destroyed-3.sox
    vo/aperture_ai/generic_security_camera_destroyed-4.sox
    vo/aperture_ai/generic_security_camera_destroyed-5.sox
)

# Localized sounds which are not localized in this language
set(RUSSIAN_EXCLUDED_LOCALIZED_SOUND_SCRIPTS
    npc/turret_floor/turret_active_2.sox
    npc/turret_floor/turret_active_4.sox
    npc/turret_floor/turret_active_5.sox
    npc/turret_floor/turret_active_6.sox
    npc/turret_floor/turret_active_7.sox
    npc/turret_floor/turret_active_8.sox
    npc/turret_floor/turret_autosearch_2.sox
    npc/turret_floor/turret_autosearch_4.sox
    npc/turret_floor/turret_autosearch_5.sox
    npc/turret_floor/turret_autosearch_6.sox
    npc/turret_floor/turret_collide_2.sox
    npc/turret_floor/turret_collide_3.sox
    npc/turret_floor/turret_collide_4.sox
    npc/turret_floor/turret_collide_5.sox
    npc/turret_floor/turret_deploy_2.sox
    npc/turret_floor/turret_deploy_4.sox
    npc/turret_floor/turret_deploy_5.sox
    npc/turret_floor/turret_deploy_6.sox
    npc/turret_floor/turret_disabled_4.sox
    npc/turret_floor/turret_disabled_5.sox
    npc/turret_floor/turret_disabled_6.sox
    npc/turret_floor/turret_disabled_7.sox
    npc/turret_floor/turret_disabled_8.sox
    npc/turret_floor/turret_search_2.sox
    npc/turret_floor/turret_search_4.sox
    npc/turret_floor/turret_pickup_3.sox
    npc/turret_floor/turret_pickup_6.sox
    npc/turret_floor/turret_pickup_7.sox
    npc/turret_floor/turret_pickup_8.sox
    npc/turret_floor/turret_pickup_9.sox
    npc/turret_floor/turret_pickup_10.sox
    npc/turret_floor/turret_retire_2.sox
    npc/turret_floor/turret_retire_4.sox
    npc/turret_floor/turret_retire_5.sox
    npc/turret_floor/turret_retire_6.sox
    npc/turret_floor/turret_retire_7.sox
    npc/turret_floor/turret_tipped_4.sox
    npc/turret_floor/turret_tipped_5.sox
    npc/turret_floor/turret_tipped_6.sox
)

set(MUSIC_SCRIPTS
    music/portal_android_hell.sox
    music/portal_no_cake_for_you.sox
    music/portal_procedural_jiggle_bone.sox
    music/portal_self_esteem_fund.sox
    music/portal_still_alive.sox
    music/portal_subject_name_here.sox
    music/portal_taste_of_blood.sox
)

set(INSTRUMENT_BANKS
    ambient/atmosphere/ambience_base.ins
    ambient/machines/beam_platform_loop1.ins
    ambient/machines/fluorescent_hum_1.ins
    ambient/music/looping_radio_mix.ins
    doors/door_metal_medium_open1.ins
    npc/turret_floor/shoot1.ins
    vehicles/apc/apc_idle1.ins
    vehicles/fast_windloop1.ins
    weapons/physcannon/energy_sing_loop4.ins
)
